import { Property } from '../types';

export const COMPANY_INFO = {
  location: 'Rajahmundry, Andhra Pradesh',
  phone: '+91-9100677906',
  email: 'rrdevelopers23@gmail.com',
  yearEstablished: '2010',
};

export const PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Premium Open Plot',
    type: 'Open Site',
    price: 13500,
    area: 183,
    areaUnit: 'sq.yrds',
    location: 'Bommuru, Rajahmundry',
    facing: 'East',
    description: 'Prime location open plot with excellent connectivity and all amenities nearby.',
    features: ['Corner Plot', 'Gated Community', '24/7 Security', 'All Utilities Available'],
    amenities: ['Street Lighting', 'Underground Drainage', 'Paved Roads'],
    parking: 'Public Parking Nearby',
    proximity: {
      hospitals: '2 km to Apollo Hospital',
      restaurants: '1 km to Local Dining Hubs',
      parks: '0.5 km to Central Park',
      airport: '15 km to Rajahmundry Airport',
      busStand: '3 km to Rajahmundry Bus Stand',
      railwayStation: '4 km to Rajahmundry Railway Station',
    },
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Luxury Villa in Kadiyapulanka',
    type: 'Villa',
    price: 8500000,
    area: 2400,
    areaUnit: 'sq.ft',
    location: 'Kadiyapulanka, Rajahmundry',
    facing: 'North-East',
    description: 'A modern luxury villa with spacious interiors, premium finishes, and a private garden.',
    features: ['3 Bedrooms', 'Modular Kitchen', 'Private Garden', 'Smart Home Features'],
    amenities: ['Swimming Pool', 'Gym', 'Gated Community', '24/7 Security'],
    parking: '2 Covered Parking Spaces',
    proximity: {
      hospitals: '3 km to Apollo Hospital',
      restaurants: '2 km to Local Dining Hubs',
      parks: '1 km to Kadiyapulanka Park',
      airport: '14 km to Rajahmundry Airport',
      busStand: '4 km to Rajahmundry Bus Stand',
      railwayStation: '5 km to Rajahmundry Railway Station',
    },
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: '3',
    title: 'Independent House in Danavaipeta',
    type: 'Individual House',
    price: 6500000,
    area: 1800,
    areaUnit: 'sq.ft',
    location: 'Danavaipeta, Rajahmundry',
    facing: 'West',
    description: 'A well-designed independent house perfect for families, with ample ventilation and parking.',
    features: ['4 Bedrooms', 'Terrace', 'Spacious Living Area', 'Vastu Compliant'],
    amenities: ['Street Lighting', 'Underground Drainage', 'Paved Roads'],
    parking: '1 Covered Parking Space',
    proximity: {
      hospitals: '1 km to Apollo Hospital',
      restaurants: '0.5 km to Local Dining Hubs',
      parks: '0.2 km to Danavaipeta Park',
      airport: '16 km to Rajahmundry Airport',
      busStand: '2 km to Rajahmundry Bus Stand',
      railwayStation: '3 km to Rajahmundry Railway Station',
    },
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: '4',
    title: 'North Facing Plot',
    type: 'Open Site',
    price: 13500,
    area: 183,
    areaUnit: 'sq.yrds',
    location: 'Lalacheruvu, Rajahmundry',
    facing: 'North',
    description: 'Vastu compliant north facing plot in a prime location.',
    features: ['Vastu Compliant', 'Good Neighborhood', 'Near to Schools', 'Easy Access'],
    amenities: ['Street Lighting', 'Underground Drainage', 'Paved Roads'],
    parking: 'Public Parking Nearby',
    proximity: {
      hospitals: '1.5 km to Apollo Hospital',
      restaurants: '1 km to Local Dining Hubs',
      parks: '0.3 km to Lalacheruvu Park',
      airport: '15 km to Rajahmundry Airport',
      busStand: '2.5 km to Rajahmundry Bus Stand',
      railwayStation: '3.5 km to Rajahmundry Railway Station',
    },
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: '5',
    title: 'Cozy Villa in Diwancheruvu',
    type: 'Villa',
    price: 7200000,
    area: 2000,
    areaUnit: 'sq.ft',
    location: 'Diwancheruvu, Rajahmundry',
    facing: 'South',
    description: 'A cozy villa with modern amenities, ideal for a small family looking for comfort.',
    features: ['2 Bedrooms', 'Open Kitchen', 'Balcony', 'Energy Efficient Design'],
    amenities: ['Community Hall', 'Gated Community', '24/7 Security'],
    parking: '1 Covered Parking Space',
    proximity: {
      hospitals: '2.5 km to Apollo Hospital',
      restaurants: '1.5 km to Local Dining Hubs',
      parks: '0.8 km to Diwancheruvu Park',
      airport: '13 km to Rajahmundry Airport',
      busStand: '3.5 km to Rajahmundry Bus Stand',
      railwayStation: '4.5 km to Rajahmundry Railway Station',
    },
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: '6',
    title: 'Spacious House in Korukonda Road',
    type: 'Individual House',
    price: 5800000,
    area: 1600,
    areaUnit: 'sq.ft',
    location: 'Korukonda Road, Rajahmundry',
    facing: 'East',
    description: 'A spacious independent house with a modern layout, close to essential amenities.',
    features: ['3 Bedrooms', 'Large Balcony', 'Modern Bathrooms', 'Natural Light'],
    amenities: ['Street Lighting', 'Underground Drainage', 'Paved Roads'],
    parking: '1 Covered Parking Space',
    proximity: {
      hospitals: '2 km to Apollo Hospital',
      restaurants: '1 km to Local Dining Hubs',
      parks: '0.4 km to Korukonda Park',
      airport: '14 km to Rajahmundry Airport',
      busStand: '3 km to Rajahmundry Bus Stand',
      railwayStation: '4 km to Rajahmundry Railway Station',
    },
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop',
  },
];
